---
- name: IPA client
  hosts: ipaclient
  become: yes
  gather_facts: true

  vars:
    ipa_domain: raibeart.loc
    ipa_realm: RAIBEART.LOC
    ipa_admin: admin
    ipa_admin_pass: ZZ12zz34
    ipa_server: ipaserver.raibeart.loc
    username: Agent007
    userpassword: testpassword
    givenname: James
    sn: Bond
    tel: 89119000000
    mail: mi6@raibeart.com
    ntp_timezone: Europe/Moscow
    
    
  tasks:

   - name: disable selinux
     selinux: 
       state: disabled

   - name: Ставим пакеты
     yum:
       name: "{{ packages }}"
       state: present
     vars:
       packages:
       - ntp
       - tzdata

   - name: Отключаем chrony
     systemd:
       name: chronyd
       enabled: false

   - name: Ставим временную зону
     timezone:
       name: "{{ ntp_timezone }}"

   - name: Включаем ntpd 
     systemd:
       name: ntpd
       state: restarted
       enabled: true

   - name: Установка epel
     yum:
      name: epel-release
      state: present
     tags:
      - epel-package
      - packages
  
   - name: Установка IPA client
     yum:
       name: ipa-client
       state: present
     tags:
      - install_ipa-client
    
   - name: Конфигурация IPA client
     shell: ipa-client-install -U
      --domain {{ ipa_domain }}
      --principal {{ ipa_admin }}@{{ ipa_realm }}
      --password {{ ipa_admin_pass }}
      --server {{ ipa_server }}
      --realm {{ ipa_realm }}
      --force-join
      --mkhomedir
     tags:
       - configure_ipa-client

   - name: Создадим обычного пользователя
     user:
       name: "{{ username }}"
       password: "{{ userpassword | password_hash('sha512') }}" 
       state: present
       update_password: on_create
       create_home: yes
       generate_ssh_key: yes

   - name: Считаем полученный публичный ключ
     shell: cat /home/{{ username }}/.ssh/id_rsa.pub
     register: userkey

   - name: Добавим пользователя в freeIPA
     ignore_errors: true
     ipa_user:
       name: "{{ username }}"
       state: present
       givenname: "{{ givenname }}"
       sn: "{{ sn }}"
       mail:
       - "{{ mail }}"
       telephonenumber:
       - "{{ tel }}"
       sshpubkey:
       - "{{ userkey.stdout }}"
       ipa_host: "{{ ipa_server }}"
       ipa_user: "{{ ipa_admin }}"
       ipa_pass: "{{ ipa_admin_pass }}" 
       
   - name: Разрешаем Firewalld
     firewalld: service={{ item }} permanent=true state=enabled
     with_items:
       - http
       - https
       - ldaps
       - ntp
       - ldap
       - kerberos
       - kpasswd
       - dns
     notify: reload firewalld

  handlers:
    
   - name: reload firewalld
     systemd:
       name: firewalld
       state: reloaded
       
 
