---
- name: IPA server
  hosts: ipaserver
  become: yes
  gather_facts: true

  vars:

    ipa_domain: raibeart.loc
    ipa_realm: RAIBEART.LOC
    ipa_admin: admin
    ipa_admin_pass: ZZ12zz34
    ipa_server: ipaserver.raibeart.loc
    ntp_timezone: Europe/Moscow
    
  tasks:

   - name: disable selinux
     selinux: 
       state: disabled

   - name: install packages
     yum:
       name: "{{ packages }}"
       state: present
     vars:
       packages:
       - ntp
       - tzdata

   - name: Disable chrony
     systemd:
       name: chronyd
       enabled: false

   - name: Set timezone
     timezone:
       name: "{{ ntp_timezone }}"

   - name: Enable ntpd 
     systemd:
       name: ntpd
       state: restarted
       enabled: true

   - name: Install FreeIPA server
     yum:
       name: ipa-server
       state: present
     tags:
      - install_ipa-server
    
   - name: Create config FreeIPA server
     shell: ipa-server-install -U
      --hostname={{ ipa_server }}
      --domain={{ ipa_domain }}
      --realm={{ ipa_realm }}
      --ds-password={{ ipa_admin_pass }}
      --admin-password={{ ipa_admin_pass }}
     notify:
      - restart ipa services
     tags:
      - configure_ipa-server

       
   - name: Enable Firewalld
     firewalld: service={{ item }} permanent=true state=enabled
     with_items:
       - http
       - https
       - ldaps
       - ntp
       - ldap
       - kerberos
       - kpasswd
       - dns
     notify: reload firewalld
     
  handlers:
    
   - name: restart ipa services
     systemd:
       name: ipa
       state: restarted
       enabled: yes

   - name: reload firewalld
     systemd:
       name: firewalld
       state: reloaded



       
